#' @title filter out tk and recovery animal
#' @param studyid Optional when \code{xpt_dir} is set; required for SQLite. Study identifier.
#' @param path_db Optional when \code{xpt_dir} is set; path of database
#' @param fake_study optional, Boolean \cr
#' whether study generated by SENDsanitizer package. When \code{TRUE}, compile data includes all treatment arms (e.g. vehicle, HD, and any other dose levels present in DM).
#' @param xpt_dir Optional; path to a directory containing XPT files for one study (flat: xpt_dir/bw.xpt, dm.xpt, etc.).
#' @return dataframe
#'
#' @examples
#' \dontrun{
#' get_compile_data(studyid='1234123', path_db='path/to/database.db')
#' get_compile_data(xpt_dir='/path/to/study_folder')
#' }
#' @export

get_compile_data <- function(studyid = NULL, path_db = NULL, fake_study = FALSE, xpt_dir = NULL) {
  use_xpt <- !is.null(xpt_dir)
  if (!use_xpt) {
    if (is.null(path_db)) stop("path_db is required when xpt_dir is not set.")
    if (is.null(studyid)) stop("studyid is required when xpt_dir is not set (SQLite).")
    studyid <- as.character(studyid)
    path <- path_db
    con <- DBI::dbConnect(RSQLite::SQLite(), dbname = path)
    con_db <- function(domain) {
      dom <- toupper(domain)
      stat <- paste0("SELECT * FROM ", dom, " WHERE STUDYID = (:x)")
      DBI::dbGetQuery(con, statement = stat, params = list(x = studyid))
    }
  }

  if (fake_study) {
    if (use_xpt) {
      dm <- read_domain_for_study("dm", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
      ts <- read_domain_for_study("ts", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    } else {
      dm <- con_db("dm")
      ts <- con_db("ts")
    }
    data.table::setDT(dm)
    data.table::setDT(ts)
    species <- ts$TSVAL[which(ts$TSPARMCD == "SPECIES")]
    dm <- dm[, c("STUDYID", "USUBJID", "SPECIES", "SEX", "ARMCD", "ARM", "SETCD")]
    dm[, `:=`(Species = species, SPECIES = NULL, ARMCD = ARM, ARM = NULL)]
    dm[ARMCD == "Control", `:=`(ARMCD = "vehicle")]
    # Keep all arms (vehicle, HD, and any other dose levels) for fake studies
    data.table::setDF(dm)
    return(dm)
  }

  if (use_xpt) {
    bw <- read_domain_for_study("bw", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    dm <- read_domain_for_study("dm", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    ds <- read_domain_for_study("ds", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    ts <- read_domain_for_study("ts", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    tx <- read_domain_for_study("tx", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    pooldef <- read_domain_for_study("pooldef", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    pp <- read_domain_for_study("pp", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
  } else {
    bw <- con_db("bw")
    dm <- con_db("dm")
    ds <- con_db("ds")
    ts <- con_db("ts")
    tx <- con_db("tx")
    pooldef <- con_db("pooldef")
    pp <- con_db("pp")
  }

# # Combine into list of assigned name
  studyData <- list('bw' = bw, 'dm' = dm, 'ds' = ds,
                    'pooldef' = pooldef,
                    'ts' = ts,  'tx' = tx, 'pp' = pp)
    #..Creation of compilation data...(Compilation of DM Data).........
    # Step-1 :: # CompileData is basically the compilation of DM data
    CompileData <- data.frame(STUDYID = NA, Species = NA,
                              USUBJID = NA, SEX = NA, ARMCD = NA, SETCD = NA)

    #Pull all of the relevant DM Data
    Species <- ts$TSVAL[which(ts$TSPARMCD == "SPECIES")]
    TRTName <- ts$TSVAL[which(ts$TSPARMCD == "TRT")]
    Duration <-ts$TSVAL[which(ts$TSPARMCD == "DOSDUR")]

    # Convert duration to days
    if (any(grepl("W",Duration)) ==TRUE){
      days <- as.numeric(gsub("\\D","",Duration))*7
    } else if (any(grepl("M",Duration)) == TRUE){
      days <- as.numeric(gsub("\\D","",Duration))*7*30
    } else {
      days <- as.numeric(gsub("\\D","",Duration))
    }
    Duration <- paste0(days,"D")

    # Make StudyID
    STUDYID <- unique(ts$STUDYID)

    # CREATE DM DATA
    DMData <- data.frame(STUDYID = rep(STUDYID, length(dm$USUBJID)),
                         Species = rep(Species, length(dm$USUBJID)),
                         USUBJID = dm$USUBJID,
                         SEX = dm$SEX,
                         ARMCD = dm$ARMCD,
                         SETCD = dm$SETCD)

    #Add to CompileData
    CompileData <- rbind(CompileData, DMData)

    # Remove NAs from the first line
    CompileData <- stats::na.omit(CompileData)

    # Create a copy of CompileData which will not
  # changes with changing the CompileData
    CompileData_copy <- data.frame(CompileData)


    # Step-2 :: # REMOVE THE RECOVERY ANIMALS from "CompileData"...<>"Recovery
  #  animals" cleaning.. using "DS domain"
    ## cat("Displaying unique values in ds$DSDECOD before filtering :\n")
    ## print(unique(ds$DSDECOD))

    # filter for specific "DSDECOD" values...( Keep the mentioned four ) ...
    filtered_ds <- ds %>%
      dplyr::filter(DSDECOD %in% c('TERMINAL SACRIFICE',
                                   'MORIBUND SACRIFICE',
                                   'REMOVED FROM STUDY ALIVE',
                                   'NON-MORIBUND SACRIFICE'))
    # check the unique value in "DSDECOD" column
    ## cat("Displaying unique values in ds$DSDECOD after filtering:\n")
    ## print(unique(filtered_ds$DSDECOD))

    #Filter "CompileData" to keep rows where USUBJID is in "filtered_ds"~~

    # Filter "CompileData" to keep rows where USUBJID is in "filtered_ds"
  # meaning removing recovery animals
    recovery_cleaned_CompileData <- CompileData %>%
      dplyr::filter(USUBJID %in% filtered_ds$USUBJID)


    # Step-3 :: # REMOVE THE TK ANIMALS IF SPECIES IS RAT from the
   # "recovery_cleaned_CompileData"
    # Initialize an empty data frame to store the results
    tK_animals_df <- data.frame(PP_PoolID = character(), STUDYID = character(),
                                USUBJID = character(), POOLID = character(),
                                stringsAsFactors = FALSE)

    # Initialize a data frame to keep track of studies with no POOLID
    no_poolid_studies <- data.frame(STUDYID = character(),
                                    stringsAsFactors = FALSE)

    # check for the species [# Check if the current study is a rat]
  # [{# Convert Species to lowercase for case-insensitive comparison}]

    Species_lower <- tolower(Species)

    if ("rat" %in% Species_lower) {
      # Create TK individuals for "Rat" studies [# Retrieve unique
      # pool IDs (TKPools) from pp table]
      TKPools <- unique(pp$POOLID)

      # Check if TKPools is not empty
      if (length(TKPools) > 0) {
# For each pool ID in TKPools, retrieve corresponding rows from pooldef table
        for (pool_id in TKPools) {
          pooldef_data <- pooldef[pooldef$POOLID == pool_id, ]

          # Create a temporary data frame if pooldef_data is not empty
          if (nrow(pooldef_data) > 0) {
            temp_df <- data.frame(PP_PoolID = pool_id,
                                  STUDYID = pooldef_data$STUDYID,
                                  USUBJID = pooldef_data$USUBJID,
                                  POOLID = pooldef_data$POOLID,
                                  stringsAsFactors = FALSE)

            # Append the temporary data frame to the results data frame
            tK_animals_df <- rbind(tK_animals_df, temp_df)
          }
        }
      } else {
        # Retrieve STUDYID for the current study
        current_study_id <- bw$STUDYID[1]

        # Add study to no_poolid_studies dataframe
        no_poolid_studies <- rbind(no_poolid_studies,
                                   data.frame(STUDYID = current_study_id,
                                              stringsAsFactors = FALSE))
      }

    } else {
      # Create a empty data frame named "tK_animals_df"
      tK_animals_df <- data.frame(PP_PoolID = character(),
                                  STUDYID = character(),
                                  USUBJID = character(),
                                  POOLID = character(),
                                  stringsAsFactors = FALSE)
    }


    # Subtract "TK_animals_df" data from the "recovery_cleaned_CompileData"
 cleaned_CompileData <- recovery_cleaned_CompileData[
   !(recovery_cleaned_CompileData$USUBJID %in% tK_animals_df$USUBJID),]



    # Dose ranking labels all arms (vehicle, HD, Intermediate, Both) for cleaned_CompileData

    # tx table  filter by TXPARMCD
  cleaned_CompileData_filtered_tx <- tx %>%
    dplyr::filter(TXPARMCD == "TRTDOS")


    # Assign the dose level for
  # "cleaned_CompileData_filtered_tx"

    # Step 1:  Create a unified separator pattern
    clean_pattern <- ";|\\||-|/|:|,"

    # Split and expand the TXVAL column, and add row_state
  clean_tx_expanded <- cleaned_CompileData_filtered_tx %>%
    dplyr::mutate(
             is_split = stringr::str_detect(TXVAL,
                                            clean_pattern),
             TXVAL = strsplit(as.character(TXVAL),
                              clean_pattern)
           ) %>%
    tidyr::unnest(TXVAL) %>%
    dplyr::mutate(
             TXVAL = as.numeric(TXVAL),
             row_state = ifelse(is_split, "new_row", "old_row")
           ) %>%
    dplyr::select(-is_split) # Remove the is_split column

    # One row per (STUDYID, SETCD) with one dose value per arm; all arms kept for join
    dose_ranking <- clean_tx_expanded %>%
      dplyr::group_by(STUDYID, SETCD) %>%
      dplyr::summarise(TXVAL = min(TXVAL, na.rm = TRUE), .groups = "drop")
    dose_ranking$TXVAL[is.infinite(dose_ranking$TXVAL)] <- NA_real_

    # Assign vehicle / HD / Intermediate / Both from study-level min/max TXVAL
    DOSE_RANKED_selected_rows <- dose_ranking %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        MinTXVAL = min(TXVAL),
        MaxTXVAL = max(TXVAL),
        DOSE_RANKING = dplyr::case_when(
          TXVAL == MinTXVAL & TXVAL == MaxTXVAL ~ "Both",
          TXVAL == MinTXVAL ~ "vehicle",
          TXVAL == MaxTXVAL ~ "HD",
          TRUE ~ "Intermediate"
        )
      ) %>%
      dplyr::select(-MinTXVAL, -MaxTXVAL) %>%
      dplyr::ungroup()

    #Merging "DOSE_RANKED_selected_rows" and "cleaned_CompileData" data framed
    dose_rank_comp_data <- dplyr::inner_join(cleaned_CompileData,
                                             DOSE_RANKED_selected_rows,
                                             by = c("STUDYID", "SETCD"))

    # rename the Data frame
    master_CompileData1 <- dose_rank_comp_data [,c("STUDYID",
                                                   "USUBJID",
                                                   "Species",
                                                   "SEX",
                                                   "DOSE_RANKING",
                                                   "SETCD")]

    # Rename the "DOSE_RANKING" column to ARMCD
    # Rename "DOSE_RANKING" to "ARMCD" in master_CompileData
    master_CompileData <- master_CompileData1 %>%
      dplyr::rename(ARMCD = DOSE_RANKING)

  master_CompileData
}
