## This code is to get score

## -----------------------------------------------------------------------------
##   Date                     Programmer
## ----------   --------------------------------------------------------------
##   Mar-31-2024    Md Yousuf Ali (md.ali@fda.hhs.gov)

#' @title get all score
#' @param studyid Mandatory, character \cr
#'   Studyid number
#' @param path_db Optional when \code{xpt_dir} is set; path of database
#' @param domain Mandatory, character or vector \cr
#'   either string or vector of domain name
#' @param fake_study optional, Boolean \cr
#'   whether study generated by SENDsanitizer package
#' @param xpt_dir Optional; root of nested XPT layout (\code{xpt_dir/APPID/STUDYID/*.xpt}). When set, \code{appid} is required.
#' @param appid Optional; application ID (folder name under \code{xpt_dir}). Required when \code{xpt_dir} is set.
#' @return list with scores per domain
#'
#' @examples
#' \dontrun{
#' get_all_score(studyid='1234123', path_db='path/to/database.db', domain=c('lb'))
#' get_all_score(studyid='STUDY1', xpt_dir='/path/to/xpt_root', appid='APP1', domain=c('lb'))
#' }
#' @export

get_all_score <- function(studyid, path_db = NULL, domain = c("lb", "mi", "bw"),
                          fake_study = FALSE, xpt_dir = NULL, appid = NULL) {
  studyid <- as.character(studyid)
  if (!is.null(path_db)) path_db <- fs::path(path_db)
  domain_len <- length(domain)
  result_return <- list(studyid_res = studyid)
  for (i in seq_len(domain_len)) {
    cur_dom <- domain[i]
    if (cur_dom == "lb") {
      df <- get_lb_score(studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir, appid = appid)
    } else if (cur_dom == "mi") {
      df <- get_mi_score(studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir, appid = appid)
    } else if (cur_dom == "bw") {
      df <- get_bw_score(studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir, appid = appid)
    } else {
      stop("check your domain")
    }
    result_return[[cur_dom]] <- df
  }
  result_return
}
