
#' @title get BW score for a given study
#' @description Uses a unified day column for BW: VISITDY, or BWNOMDY, or BWDY (in that order). BWNOMLBL is not required; optional columns are used only if present. Scores are computed for all subjects (all treatment arms). Z-scores use vehicle as the reference (mean and SD from \code{ARMCD == "vehicle"}).
#' @param studyid Optional when \code{xpt_dir} is set; required for SQLite. Study identifier.
#' @param path_db Optional when \code{xpt_dir} is set; path of database
#' @param fake_study optional, Boolean \cr
#' whether study generated by SENDsanitizer package
#' @param master_CompileData optional; precomputed compile data
#' @param score_in_list_format optional; if \code{FALSE} (default), returns a long-format data frame with one score per subject per endpoint; if \code{TRUE}, returns the full wide data frame (e.g. \code{bwzscore_BW}) as before.
#' @param xpt_dir Optional; path to a directory containing XPT files for one study (flat: xpt_dir/bw.xpt, dm.xpt, etc.).
#' @param terminal_setcds_only Passed to \code{\link{get_compile_data}} when compile data is built; default \code{TRUE}.
#' @return When \code{score_in_list_format} is \code{FALSE}, a data frame with columns \code{STUDYID}, \code{USUBJID}, \code{ARMCD}, \code{SETCD}, \code{endpoint}, \code{score}, and \code{SEX} (one row per subject; endpoint is \dQuote{BW}). Rows are sorted by \code{STUDYID}, \code{endpoint}, dose tier (\code{ARMCD}), then \code{USUBJID}. When \code{TRUE}, the full wide per-subject data frame from compile data and BW: \code{USUBJID}, \code{STUDYID}, \code{BWSTRESN}, \code{BWSTRESN_Init}, \code{ARMCD}, \code{SETCD}, \code{SEX}, \code{finalbodyweight}, and \code{BWZSCORE}. Rows are sorted by \code{STUDYID}, dose tier (\code{ARMCD}), then \code{USUBJID}.
#'
#' @examples
#' \dontrun{
#' get_bw_score(studyid='1234123', path_db='path/to/database.db')
#' get_bw_score(xpt_dir='/path/to/study_folder')
#' }
#' @export

get_bw_score <- function(studyid = NULL,
                         path_db = NULL,
                         fake_study = FALSE,
                         master_CompileData = NULL,
                         score_in_list_format = FALSE,
                         xpt_dir = NULL,
                         terminal_setcds_only = TRUE) {
  use_xpt <- !is.null(xpt_dir)
  if (!use_xpt) {
    if (is.null(path_db)) stop("path_db is required when xpt_dir is not set.")
    if (is.null(studyid)) stop("studyid is required when xpt_dir is not set (SQLite).")
    studyid <- as.character(studyid)
  }
  if (use_xpt) {
    bw <- read_domain_for_study("bw", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    ts <- read_domain_for_study("ts", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    pooldef <- read_domain_for_study("pooldef", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
    pp <- read_domain_for_study("pp", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
  } else {
    path <- path_db
    con <- DBI::dbConnect(RSQLite::SQLite(), dbname = path)
    con_db <- function(domain) {
      dom <- toupper(domain)
      stat <- paste0("SELECT * FROM ", dom, " WHERE STUDYID = (:x)")
      DBI::dbGetQuery(con, statement = stat, params = list(x = studyid))
    }
    bw <- con_db("bw")
    ts <- con_db("ts")
    pooldef <- con_db("pooldef")
    pp <- con_db("pp")
  }

  # Unified day column: VISITDY or BWNOMDY or BWDY (used for all BW logic)
  nm <- names(bw)
  v1 <- if ("VISITDY" %in% nm) as.numeric(bw$VISITDY) else rep(NA_real_, nrow(bw))
  v2 <- if ("BWNOMDY" %in% nm) as.numeric(bw$BWNOMDY) else rep(NA_real_, nrow(bw))
  v3 <- if ("BWDY" %in% nm) as.numeric(bw$BWDY) else rep(NA_real_, nrow(bw))
  bw$VISITDY <- dplyr::coalesce(v1, v2, v3)
  if (all(is.na(bw$VISITDY))) stop("BW domain must have at least one of VISITDY, BWNOMDY, or BWDY.")

    Species <- ts$TSVAL[which(ts$TSPARMCD == "SPECIES")]
    TRTName <- ts$TSVAL[which(ts$TSPARMCD == "TRT")]
    Duration <-ts$TSVAL[which(ts$TSPARMCD == "DOSDUR")]
    # "BodyWeight_zScore" calculation
    # Initial BW weight calculation

    StudyInitialWeights <- data.frame("STUDYID" = NA, "USUBJID" = NA,
                                      "BWSTRESN" = NA, "VISITDY" = NA,
                                      "BWBLFL" = NA)

    # Initialize dataframe for unmatched USUBJIDs
    UnmatchedUSUBJIDs <- data.frame("USUBJID" = character(), stringsAsFactors = FALSE)


    ## if (TRUE){
      # Get unique USUBJIDs in the current study
      unique_subjids <- unique(bw$USUBJID)

      for (currentUSUBJID in unique_subjids) {

        # Initialize an empty dataframe for this subject
        SubjectInitialWeight <- data.frame()

        # Data (all rows) for the current USUBJID (VISITDY already unified on bw)
        subj_data <- bw[which(bw$USUBJID == currentUSUBJID), ]
        base_cols <- c("STUDYID", "USUBJID", "BWSTRESN", "VISITDY", "BWBLFL")
        cols <- base_cols[base_cols %in% names(subj_data)]

        # 1. Check if VISITDY == 1 is present
        SubjectInitialWeight <- subj_data[subj_data$VISITDY == 1, cols, drop = FALSE]


        # 2. If no initial weight with VISITDY == 1,  try VISITDY < 0
        if (nrow(SubjectInitialWeight) == 0) {
          negative_visits <- subj_data[subj_data$VISITDY < 0, ]
          if (nrow(negative_visits) > 0) {
            closest_row <- which.min(abs(negative_visits$VISITDY))
            SubjectInitialWeight <- negative_visits[closest_row, cols, drop = FALSE]
          }
        }

        # 3. If no initial weight with VISITDY == 1 VISITDY < 0 , try 1<VISITDY<=5
        if (nrow(SubjectInitialWeight) == 0) {
          five_visitdy <- subj_data[subj_data$VISITDY > 1 & subj_data$VISITDY <= 5, ]

          if (nrow(five_visitdy) > 0) {
            # If there are rows where 1 < VISITDY <= 5, choose the one with the minimum VISITDY value
            closest_row_five <- which.min(five_visitdy$VISITDY)
            SubjectInitialWeight <- five_visitdy[closest_row_five, c("STUDYID", "USUBJID", "BWSTRESN", "VISITDY", "BWNOMDY", "BWNOMLBL", "BWBLFL")]
          }
        }

        # 4. If no rows, if VISITDY  >5 , set BWSTRESN value 0
        if (nrow(SubjectInitialWeight) == 0) {
          null_visitdy_large_bw <- subj_data[subj_data$VISITDY > 5, ]

          if (nrow(null_visitdy_large_bw) > 0) {
            # Set BWSTRESN to 0 for the rows that meet the condition
            null_visitdy_large_bw$BWSTRESN <- 0

            # Choose the row with the minimum VISITDY value greater than 5
            closest_row_null_visitdy <- which.min(null_visitdy_large_bw$VISITDY)
            SubjectInitialWeight <- null_visitdy_large_bw[closest_row_null_visitdy, cols, drop = FALSE]
          }
        }
        # If SubjectInitialWeight is still empty, add currentUSUBJID to UnmatchedUSUBJIDs
        if (nrow(SubjectInitialWeight) == 0) {
          UnmatchedUSUBJIDs <- rbind(UnmatchedUSUBJIDs, data.frame(USUBJID = currentUSUBJID, stringsAsFactors = FALSE))
        }
        # Store Values to "StudyInitialWeights" data frame
        StudyInitialWeights <- rbind(StudyInitialWeights,SubjectInitialWeight)
      }
    ## }

    # remove the first row (initialized with NAs)
    StudyInitialWeights <- StudyInitialWeights[-1, ]


    #Check for the presence of duplicate "USUBJID" in "StudyInitialWeights"

    # Check for any duplicate USUBJID
    duplicates_exist <- any(duplicated(StudyInitialWeights$USUBJID))

    #  see the duplicate values
    if (duplicates_exist) {
      duplicate_usubjids <- StudyInitialWeights$USUBJID[duplicated(StudyInitialWeights$USUBJID)]
    }

    # Duplicate rows handling

    # Removing duplicates based on specific column(s)
    # only the first occurrence of each unique USUBJID will be kept, and subsequent duplicates will be removed
    StudyInitialWeights <- StudyInitialWeights[!duplicated(StudyInitialWeights$USUBJID), ]


    # Final day "StudyBodyWeights" calculation

    #(StudyBodyWeights)-(TERMBW)-(BoDY Weigt) calculation

    # Initialize "StudyBodyWeights" empty data frame
    StudyBodyWeights <- data.frame("STUDYID" = NA, "USUBJID" = NA, "BWTESTCD" = NA,
                                   "BWSTRESN" = NA, "VISITDY" = NA, "BWBLFL" = NA)

    # Initialize dataframe for unmatched USUBJIDs
    BodyWeights_UnmatchedUSUBJIDs <- data.frame("USUBJID" = character(), stringsAsFactors = FALSE)


    if(TRUE) {
      # Get unique USUBJIDs in the current study
      unique_bw_subjids <- unique(bw$USUBJID)

      for (current_bw_USUBJID in unique_bw_subjids) {

        # Initialize an empty dataframe for this subject
        SubjectBodyWeight <- data.frame()

        # Data (all rows) for the current USUBJID (VISITDY already unified on bw)
        subj_bw_data <- bw[which(bw$USUBJID == current_bw_USUBJID), ]
        body_cols <- c("STUDYID", "USUBJID", "BWTESTCD", "BWSTRESN", "VISITDY", "BWBLFL")
        body_cols <- body_cols[body_cols %in% names(subj_bw_data)]

        # 1. Check if BWTESTCD == TERMBW is present
        SubjectBodyWeight <- subj_bw_data[subj_bw_data$BWTESTCD == "TERMBW", body_cols, drop = FALSE]

        # 2. If no BWTESTCD == TERMBW, try VISITDY > 5
        if (nrow(SubjectBodyWeight) == 0) {
          positive_bw_VISITDY <- subj_bw_data[subj_bw_data$VISITDY > 5, ]

          if (nrow(positive_bw_VISITDY) > 0) {
            # choose the one with the maximum VISITDY value
            max_VISITDY <- which.max(positive_bw_VISITDY$VISITDY)
            SubjectBodyWeight <- positive_bw_VISITDY[max_VISITDY, body_cols, drop = FALSE]
          }
        }

        # If SubjectInitialWeight is still empty, add currentUSUBJID to UnmatchedUSUBJIDs
        if (nrow(SubjectBodyWeight) == 0) {
          BodyWeights_UnmatchedUSUBJIDs <- rbind(BodyWeights_UnmatchedUSUBJIDs, data.frame(USUBJID = current_bw_USUBJID, stringsAsFactors = FALSE))
        }

        # Store Values to "StudyBodyWeights" data frame
        StudyBodyWeights  <- rbind(StudyBodyWeights ,SubjectBodyWeight)
      }
    }

    # Remove the first row (initialized with NAs)
    StudyBodyWeights <- StudyBodyWeights[-1, ]


    #Check for the presence of duplicate "USUBJID" in "StudyBodyWeights"

    # Check for any duplicate USUBJID
    stbw_duplicates_exist <- any(duplicated(StudyBodyWeights$USUBJID))

    # See the duplicate values
    if (stbw_duplicates_exist) {
      stbw_duplicate_usubjids <- StudyBodyWeights$USUBJID[duplicated(StudyBodyWeights$USUBJID)]
    }

    # Duplicate "StudyBodyWeights" rows handling

    # Removing duplicates based on specific column(s)
    # only the first occurrence of each unique USUBJID will be kept, and subsequent duplicates will be removed
    # StudyBodyWeights <- StudyBodyWeights[!duplicated(StudyBodyWeights$USUBJID), ]

    # number of unique USUBJID
    unique_StudyBodyWeights_USUBJID <- length(unique(StudyBodyWeights$USUBJID))
    #


####################~~~~~~~~~~~~~~~~~~~~~~~tk_animal_take_care~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#####
# 
#     tK_animals_df <- data.frame(PP_PoolID = character(), STUDYID = character(),
#                                 USUBJID = character(), POOLID = character(),
#                                 stringsAsFactors = FALSE)
# 
#     # Initialize a data frame to keep track of studies with no POOLID
#     no_poolid_studies <- data.frame(STUDYID = character(),
#                                     stringsAsFactors = FALSE)
# 
#     # check for the species [# Check if the current study is a rat]
#   # [{# Convert Species to lowercase for case-insensitive comparison}]
# 
#     Species_lower <- tolower(Species)
# 
#     if ("rat" %in% Species_lower) {
#       # Create TK individuals for "Rat" studies [# Retrieve unique
#       # pool IDs (TKPools) from pp table]
#       TKPools <- unique(pp$POOLID)
# 
#       # Check if TKPools is not empty
#       if (length(TKPools) > 0) {
# # For each pool ID in TKPools, retrieve corresponding rows from pooldef table
#         for (pool_id in TKPools) {
#           pooldef_data <- pooldef[pooldef$POOLID == pool_id, ]
# 
#           # Create a temporary data frame if pooldef_data is not empty
#           if (nrow(pooldef_data) > 0) {
#             temp_df <- data.frame(PP_PoolID = pool_id,
#                                   STUDYID = pooldef_data$STUDYID,
#                                   USUBJID = pooldef_data$USUBJID,
#                                   POOLID = pooldef_data$POOLID,
#                                   stringsAsFactors = FALSE)
# 
#             # Append the temporary data frame to the results data frame
#             tK_animals_df <- rbind(tK_animals_df, temp_df)
#           }
#         }
#       } else {
#         # Retrieve STUDYID for the current study
#         current_study_id <- bw$STUDYID[1]
# 
#         # Add study to no_poolid_studies dataframe
#         no_poolid_studies <- rbind(no_poolid_studies,
#                                    data.frame(STUDYID = current_study_id,
#                                               stringsAsFactors = FALSE))
#       }
# 
#     } else {
#       # Create a empty data frame named "tK_animals_df"
#       tK_animals_df <- data.frame(PP_PoolID = character(),
#                                   STUDYID = character(),
#                                   USUBJID = character(),
#                                   POOLID = character(),
#                                   stringsAsFactors = FALSE)
#     }
    ####################~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #############################

#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  #<><><><><><><><><><><><><><><><>... Remove TK animals and Recovery animals......<><><><><><>.............
    #<><><><><><><><> master_CompileData is free of TK animals and Recovery animals<><><><><><><><><><><><><><>
    
    # get-master-compile-data~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #browser()
    # Check if master_CompileData is NULL
    if (is.null(master_CompileData)) {
      fake_study = fake_study
      # Call the master_CompileData function to generate the data frame
      master_CompileData <- get_compile_data(studyid = studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir,
                                           terminal_setcds_only = terminal_setcds_only)
    } 
    
    # # Remove the TK animals and Recovery animals
    # LB_tk_recovery_filtered <- max_visitdy_df %>%
    #   dplyr::filter(USUBJID %in% master_CompileData$USUBJID)
    # 
    # # Perform a left join to match USUBJID and get ARMCD ## 020924
    # #-inner_join() used instead of left_join()#199
    # LB_tk_recovery_filtered_ARMCD <- LB_tk_recovery_filtered %>%
    #   dplyr::inner_join(master_CompileData %>% dplyr::select(USUBJID, ARMCD), by = "USUBJID")
    
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    


    #Substract TK animals from the "StudyInitialWeights" and StudyBodyWeights" data frame
    #tk_less_StudyBodyWeights <- StudyBodyWeights[!(StudyBodyWeights$USUBJID %in% tK_animals_df$USUBJID),]
    
    tk_less_StudyBodyWeights <- StudyBodyWeights[(StudyBodyWeights$USUBJID %in% master_CompileData$USUBJID),]

    # Substract TK animals from the "StudyInitialWeights" data frame
    #tk_less_StudyInitialWeights <- StudyInitialWeights[!(StudyInitialWeights$USUBJID %in% tK_animals_df$USUBJID),]
    tk_less_StudyInitialWeights <- StudyInitialWeights[(StudyInitialWeights$USUBJID %in% master_CompileData$USUBJID),]

    # Rename columns in StudyInitialWeights by adding "_Init" suffix
    names(tk_less_StudyInitialWeights) <- ifelse(names(tk_less_StudyInitialWeights) == "USUBJID",
                                                 "USUBJID",
                                                 paste0(names(tk_less_StudyInitialWeights), "_Init"))

    #  Inner join"StudyInitialWeights" and StudyBodyWeights"
    # an inner join on the USUBJID column for TK_less (StudyInitialWeights & StudyBodyWeights )
    joined_BW_df <- merge(tk_less_StudyBodyWeights, tk_less_StudyInitialWeights, by = "USUBJID")


    # Select specific columns from joined_BW_df
    BW_df_selected_column <- joined_BW_df[, c("USUBJID", "STUDYID", "BWSTRESN", "BWSTRESN_Init")]

    # Add "ARMCD","SETCD","SEX" to "selected_df"
    master_CompileData <- get_compile_data(studyid = studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir,
                                           terminal_setcds_only = terminal_setcds_only)
    STUDYID_less_master_CompileData <- master_CompileData[, c("USUBJID", "ARMCD","SETCD","SEX")]
    BW_df_merged_ARMCD <- merge(BW_df_selected_column, STUDYID_less_master_CompileData, by = "USUBJID")

    #"Recovery animals" cleaning from "BW_df_merged_ARMCD"
    # #  master_CompileData is alreadyTK animals & Recovery animal cleaned

    # "BWzScore Calculation"

    # Create the finalbodyweight column in merged_recovery_tk_cleaned_dose_ranked_df data frame
    # XPT/SQLite may return BWSTRESN as character; coerce before arithmetic
    bwzscore_BW_df <- BW_df_merged_ARMCD %>%
      dplyr::mutate(
        BWSTRESN = as.numeric(BWSTRESN),
        BWSTRESN_Init = as.numeric(BWSTRESN_Init),
        finalbodyweight = abs(BWSTRESN - BWSTRESN_Init)
      )
#browser()
    # Create the BWZSCORE column
    bwzscore_BW <- bwzscore_BW_df %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle = mean(finalbodyweight[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle = stats::sd(finalbodyweight[ARMCD == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        BWZSCORE = (finalbodyweight - mean_vehicle) / sd_vehicle
      ) %>%
      dplyr::select(-mean_vehicle, -sd_vehicle)  # Optionally remove the mean_vehicle and sd_vehicle columns

    bwzscore_BW <- bwzscore_BW %>%
      dplyr::mutate(.armcd_ord = armcd_sort_key(.data$ARMCD)) %>%
      dplyr::arrange(.data$STUDYID, .data$.armcd_ord, .data$USUBJID) %>%
      dplyr::select(-.data$.armcd_ord)
    
    # Per-subject-per-endpoint long format (all subjects, all arms)
    bw_per_subject_endpoint <- bwzscore_BW %>%
      dplyr::mutate(endpoint = "BW", score = BWZSCORE) %>%
      dplyr::select(STUDYID, USUBJID, ARMCD, SETCD, endpoint, score, SEX) %>%
      dplyr::mutate(.armcd_ord = armcd_sort_key(.data$ARMCD)) %>%
      dplyr::arrange(.data$STUDYID, .data$endpoint, .data$.armcd_ord, .data$USUBJID) %>%
      dplyr::select(-.data$.armcd_ord)
    
    # Return based on score_in_list_format
    if (score_in_list_format) {
      return(bwzscore_BW)
    } else {
      return(bw_per_subject_endpoint)
    }

}
