## This code is to get score

## -----------------------------------------------------------------------------
##   Date                     Programmer
## ----------   --------------------------------------------------------------
##   Mar-31-2024    Md Yousuf Ali (md.ali@fda.hhs.gov)

#' @title get all score
#' @param studyid Optional when \code{xpt_dir} is set; required for SQLite. Study identifier.
#' @param path_db Optional when \code{xpt_dir} is set; path of database
#' @param domain character or vector; domain name(s) to score (e.g. "lb", "mi", "bw").
#' @param fake_study optional, Boolean; whether study generated by SENDsanitizer package
#' @param xpt_dir Optional; path to a directory containing XPT files for one study (flat: xpt_dir/bw.xpt, dm.xpt, etc.).
#' @return list with scores per domain
#'
#' @examples
#' \dontrun{
#' get_all_score(studyid='1234123', path_db='path/to/database.db', domain=c('lb'))
#' get_all_score(xpt_dir='/path/to/study_folder', domain=c('lb'))
#' }
#' @export

get_all_score <- function(studyid = NULL, path_db = NULL, domain = c("lb", "mi", "bw"),
                          fake_study = FALSE, xpt_dir = NULL) {
  use_xpt <- !is.null(xpt_dir)
  if (!use_xpt && is.null(studyid)) stop("studyid is required when xpt_dir is not set (SQLite).")
  if (use_xpt) {
    studyid_res <- if (!is.null(studyid)) as.character(studyid) else basename(xpt_dir)
  } else {
    studyid_res <- as.character(studyid)
  }
  if (!is.null(path_db)) path_db <- fs::path(path_db)
  domain_len <- length(domain)
  result_return <- list(studyid_res = studyid_res)
  for (i in seq_len(domain_len)) {
    cur_dom <- domain[i]
    if (cur_dom == "lb") {
      df <- get_lb_score(studyid = studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir)
    } else if (cur_dom == "mi") {
      df <- get_mi_score(studyid = studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir)
    } else if (cur_dom == "bw") {
      df <- get_bw_score(studyid = studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir)
    } else {
      stop("check your domain")
    }
    result_return[[cur_dom]] <- df
  }
  result_return
}
