
#' @title get MI score for a given study
#' @description Scores are computed for all subjects (all treatment arms). Study-level MI score is the average of per-subject highest finding scores across all arms.
#' @param studyid Optional when \code{xpt_dir} is set; required for SQLite. Study identifier.
#' @param path_db Optional when \code{xpt_dir} is set; path of database
#' @param fake_study optional, Boolean \cr
#' whether study generated by SENDsanitizer package
#' @param master_CompileData optional; precomputed compile data
#' @param score_in_list_format optional; if \code{FALSE} (default), returns a long-format data frame with one score per subject per endpoint; if \code{TRUE}, returns a per-subject wide data frame (one row per subject, one column per finding score), similar to \code{get_bw_score}.
#' @param xpt_dir Optional; path to a directory containing XPT files for one study (flat: xpt_dir/mi.xpt, etc.).
#' @param terminal_setcds_only Passed to \code{\link{get_compile_data}} when compile data is built; default \code{TRUE}.
#' @return When \code{score_in_list_format} is \code{FALSE}, a data frame with columns \code{STUDYID}, \code{USUBJID}, \code{ARMCD}, \code{SETCD}, \code{SEX}, \code{endpoint}, and \code{score} (one row per subject per microscopical finding). Rows are sorted by \code{STUDYID}, \code{endpoint}, dose tier (\code{ARMCD}), then \code{USUBJID}, as in \code{get_lb_score} long output. When \code{TRUE}, a per-subject wide data frame with columns 1--6 (e.g. \code{STUDYID}, \code{USUBJID}, \code{ARMCD}, \code{SEX}) plus one column per MISTRESC with severity score and \code{highest_score}. Rows are sorted by \code{STUDYID}, dose tier (\code{ARMCD}), then \code{USUBJID}, as in \code{get_bw_score} / \code{get_lb_score} wide output.
#'
#' @examples
#' \dontrun{
#' get_mi_score(studyid='1234123', path_db='path/to/database.db')
#' get_mi_score(xpt_dir='/path/to/study_folder')
#' }
#' @export

get_mi_score <- function(studyid = NULL,
                         path_db = NULL,
                         fake_study = FALSE,
                         master_CompileData = NULL,
                         score_in_list_format = FALSE,
                         xpt_dir = NULL,
                         terminal_setcds_only = TRUE) {
  use_xpt <- !is.null(xpt_dir)
  if (!use_xpt) {
    if (is.null(path_db)) stop("path_db is required when xpt_dir is not set.")
    if (is.null(studyid)) stop("studyid is required when xpt_dir is not set (SQLite).")
    studyid <- as.character(studyid)
  }
  if (use_xpt) {
    mi <- read_domain_for_study("mi", studyid = NULL, path_db = path_db, xpt_dir = xpt_dir)
  } else {
    con <- DBI::dbConnect(RSQLite::SQLite(), dbname = path_db)
    mi <- DBI::dbGetQuery(con, statement = "SELECT * FROM MI WHERE STUDYID = (:x)", params = list(x = studyid))
  }
    # Initialize the  MI_final_score DATA FRAME
    MI_final_score <- data.frame( STUDYID = unique(mi$STUDYID), avg_MI_score = NA )

    #Make Data Frame to hold MI Information for the STUDY available in combined_mi for repeat dose
    MIData <- data.frame("USUBJID" = NA,"MISTRESC" = NA,"MISEV" = NA,
                         "MISPEC" = NA)

    # Filter the data for the current STUDYID
    mi_study_data <- mi

    #Pull all of the relevant MI Data using Grepl
    MBD <- mi_study_data[grepl("LIVER", mi_study_data$MISPEC, ignore.case = TRUE),
                         c("USUBJID", "MISTRESC","MISEV","MISPEC")]
    #Add to CompileData
    MIData <- rbind(MIData, MBD)

    # Convert empty strings to NA in the MISEV column
    MIData$MISEV[MIData$MISEV == ""] <- NA

    #MAKE NA Sev's a 0
    MIData$MISEV <-  MIData$MISEV %>% tidyr::replace_na("0")
    MIData <- stats::na.omit(MIData)

    MIData$MISTRESC <- toupper(MIData$MISTRESC)

    # # Remove the "Normal" values from the "MISTRESC" column(Subset MIData to remove rows where MISTRESC is "Normal")
    # NORMAL_DATA <- MIData[MIData$MISTRESC == "NORMAL", ] # get the rows having value "Normal"
    #
    # MIData <- MIData[MIData$MISTRESC != "NORMAL", ]

    #Convert Severity
    # Replacing various patterns in MISEV with numeric strings

    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "\\b1\\s*OF\\s*4\\b", "2")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "\\b2\\s*OF\\s*4\\b", "3")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "\\b3\\s*OF\\s*4\\b", "4")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "\\b4\\s*OF\\s*4\\b", "5")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "1 OF 5", "1")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "MINIMAL", "1")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "2 OF 5", "2")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "MILD", "2")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "3 OF 5", "3")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "MODERATE", "3")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "4 OF 5", "4")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "MARKED", "4")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "5 OF 5", "5")
    MIData$MISEV <- stringr::str_replace_all(MIData$MISEV, "SEVERE", "5")

    testing_MIData <- MIData

    # Converting MISEV to an ordered factor
    MIData$MISEV <- ordered(MIData$MISEV, levels= c("0","1", "2", "3", "4","5"))

    # Replace NA values in MISEV with "0"
    MIData$MISEV = MIData$MISEV %>% tidyr::replace_na("0")

    # Make all the MISPEC value = LIVER
    # replace all the value to Liver which will replace "LIVER/GALLBLADDER" to "LIVER"
    MIData$MISPEC <- "LIVER" # replace the "LIVER/GALLBLADDER" to "LIVER"

    #Combine Levels on Findings
    MIData$MISTRESC <- as.factor(MIData$MISTRESC)
    levels(MIData$MISTRESC)[levels(MIData$MISTRESC) == "CELL DEBRIS"] <- "CELLULAR DEBRIS"
    levels(MIData$MISTRESC)[levels(MIData$MISTRESC) == "Infiltration, mixed cell"] <- "Infiltrate"
    levels(MIData$MISTRESC)[levels(MIData$MISTRESC) == "Infiltration, mononuclear cell"] <- "Infiltrate"
    levels(MIData$MISTRESC)[levels(MIData$MISTRESC) == "INFILTRATION, MONONUCLEAR CELL"] <- "Infiltrate"
    levels(MIData$MISTRESC)[levels(MIData$MISTRESC) == "Fibrosis"] <- "Fibroplasia/Fibrosis"

    # Remove rows with empty MISTRESC
    MIData <- MIData[MIData$MISTRESC != '', ]
    #........................................................................................
    # Create a copy of MIData
    MIData_copy <- MIData

    #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    # Remove the "Recovery animals and tk animals from "MIData"
    #<><><><><><><><> master_CompileData is free of TK animals and Recovery animals<><><><><><><><><><><><><><>
    #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    # @get-master-compile-data~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #browser()
    # Check if master_CompileData is NULL
    if (is.null(master_CompileData)) {
      fake_study = fake_study
      # Call the master_CompileData function to generate the data frame
      master_CompileData <- get_compile_data(studyid = studyid, path_db = path_db, fake_study = fake_study, xpt_dir = xpt_dir,
                                           terminal_setcds_only = terminal_setcds_only)
    } 
    
    
     # master_CompileData <- get_compile_data(studyid = studyid,
     #                                   path_db = path_db,fake_study = fake_study)

    # Filter the data frame
    tk_recovery_less_MIData <- MIData %>% dplyr::filter (USUBJID %in% master_CompileData$USUBJID)

    # Perform a left join to match USUBJID and get ARMCD
    tk_recovery_less_MIData_with_ARMCD <- tk_recovery_less_MIData %>%
      dplyr::left_join(master_CompileData %>% dplyr::select(STUDYID, USUBJID, ARMCD, SETCD), by = "USUBJID")

    ########## MI Data ###############
    MIData_cleaned <- tk_recovery_less_MIData_with_ARMCD
    MIData_cleaned_copy <- MIData_cleaned

    # cat("MIData_cleaned : \n", toString(head(MIData_cleaned)), "\nDimensions:",
    #     paste(dim(MIData_cleaned), collapse = 'x'), "\n") # ..............................................................

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Merge Severity MI Data into Compile Data~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    MIIncidencePRIME <-MIData_cleaned[,c(1,2,4)]

    test_MIIncidencePRIME <- MIIncidencePRIME

    Severity <- merge(master_CompileData[,c("STUDYID","USUBJID","Species", "ARMCD")], MIData_cleaned)

    MIData_cleaned_SColmn <- MIData_cleaned %>% dplyr::select(USUBJID,MISTRESC,MISEV)

    MIData_cleaned_SColmn <- reshape2::dcast(MIData_cleaned, USUBJID ~ MISTRESC, value.var = "MISEV")

    MIData_cleaned_SColmn[is.na(MIData_cleaned_SColmn)] <- "0" #Fill NAs with Zero

    mi_CompileData <- merge(master_CompileData , MIData_cleaned_SColmn, by = "USUBJID") # Final & working mi_CompileData

    # Back-up data frame for checking  purpose
    final_working_compile_data_bef_normal <- mi_CompileData

    ## cat("mi_CompileData : \n", toString(head(MIData_cleaned)), "\nDimensions:",
    ##     paste(dim(mi_CompileData), collapse = 'x'), "\n") ### ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    # Remove Normal MI Results
    normalIndex <- which(colnames(mi_CompileData) == 'NORMAL')
    if (length(normalIndex) > 0) {
      mi_CompileData <- mi_CompileData[, -normalIndex]
    }

    # Back-up data frame for checking  purpose
    final_working_compile_data_afer_normal <- mi_CompileData

    # cat("mi_CompileData : \n", toString(head(MIData_cleaned)), "\nDimensions:",
    #     paste(dim(mi_CompileData), collapse = 'x'), "\n") ### ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    # Check the data types of the columns before conversion
    #str(mi_CompileData)

    #####????????????????????????? check the number~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    # Convert columns 7 to the last column  of mi_CompileData to numeric
    mi_CompileData[, 7:ncol(mi_CompileData)] <- sapply(mi_CompileData[, 7:ncol(mi_CompileData)], as.numeric)

    # Check the data types of the columns after conversion
    #str(mi_CompileData)


    #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@-------------------@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    print_MIIncidencePRIME <- MIIncidencePRIME
    print_mi_CompileData <- mi_CompileData

    # Here Check the number of columns in mi_CompileData
    mi_per_subject_endpoint <- data.frame(
      STUDYID = character(0), USUBJID = character(0),
      ARMCD = character(0), SETCD = character(0), SEX = character(0),
      endpoint = character(0), score = numeric(0),
      stringsAsFactors = FALSE
    )
    # Per-subject wide format (empty when ncol <= 6; filled when ncol > 6)
    mi_wide_per_subject <- mi_CompileData[, 1:6, drop = FALSE][0, ]

    if (ncol(mi_CompileData) > 6) {
      #Calculate Incidence per group for MI Data
      MIIncidencePRIME <- merge(MIIncidencePRIME, unique(mi_CompileData[,c("STUDYID","USUBJID","ARMCD")]), by = c("USUBJID"))

      # get the name of the columns of " MIIncidencePRIME"
      column_MIIncidencePRIME <- data.frame(names(MIIncidencePRIME)) # column names of MIIncidencePRIME

      # Directly subset the data frame
      MIIncidence <- MIIncidencePRIME[, c("STUDYID","USUBJID", "MISTRESC","ARMCD")]

      test_MIIncidence  <- MIIncidence

      GroupIncid <- data.frame(Treatment = NA,Sex = NA,Finding = NA,Count = NA)

      # Iterate over each unique study
      #for (Study in unique(MIIncidence$STUDYID)){

        # Iterate over sex categories
        for (sex in c('M','F')) {
          # Filter data for the current study
          StudyMI <- MIIncidence[which(MIIncidence$STUDYID==unique(MIIncidence$STUDYID)),]
          #StudyMI <- MIIncidence

          StudyGroupIncid <- data.frame(Treatment = NA,Sex = NA,Finding = NA,Count = NA)

          # Filter data for the current sex
          sexSubjects <- mi_CompileData$USUBJID[which(mi_CompileData$SEX == sex)]
          sexIndex <- which(StudyMI$USUBJID %in% sexSubjects)
          StudyMI <- StudyMI[sexIndex,]

          # Iterate over unique treatment arms (ARMCD)
          for(dose in unique(StudyMI$ARMCD)){
            doseMI <- StudyMI[which(StudyMI$ARMCD == dose),]

            # Calculate the incidence for each finding
            Incid <- data.frame(table(toupper(doseMI$MISTRESC))/length(unique(doseMI$USUBJID)))

            names(Incid)[2] <- "Count"
            names(Incid)[1] <- "Finding"
            Incid$Treatment <- paste0(unique(unique(StudyMI$STUDYID)), " ",dose)
            Incid$Sex <- sex

            StudyGroupIncid <- rbind(StudyGroupIncid,Incid)
          }

          #Removing of Vehicle Baseline
          for (finding in unique(StudyGroupIncid$Finding)) {
            findingIndex <- which(StudyGroupIncid$Finding == finding)
            vehicleIndex <- grep('Vehicle', StudyGroupIncid$Treatment[findingIndex]) # VEHICLE FOR THE CURRENT FINDINGS.....
            if (length(vehicleIndex) > 0) {
              baseline <- StudyGroupIncid$Count[findingIndex][vehicleIndex]
              StudyGroupIncid$Count[findingIndex] <- StudyGroupIncid$Count[findingIndex] - baseline
            }
          }
          negativeIndex <- which(StudyGroupIncid$Count < 0) # when findings in HD group less than the vehicle group
          if (length(negativeIndex) > 0) {
            StudyGroupIncid$Count[negativeIndex] <- 0
          }
          # Combine results
          GroupIncid <- rbind(GroupIncid, StudyGroupIncid)
        }
      #}

      removeIndex <- which(is.na(GroupIncid$Treatment))
      if (length(removeIndex) > 0) {
        GroupIncid <- GroupIncid[-removeIndex,]
      }

      MIIncidence <- GroupIncid

      # cat("MIIncidence : \n", toString(head(MIData_cleaned)), "\nDimensions:",
      #     paste(dim(MIIncidence), collapse = 'x'), "\n") #......................

      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      #~~~~~~~~~~~~~~~~~~~~~~~~Create a copy of mi_CompileData named mi_CompileData2 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      # Create a copy of mi_CompileData named mi_CompileData2
      mi_CompileData2 <- mi_CompileData #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      # Severity calculation and recalculation.........................................................................
      # Adjustment of the severity score based on the Incidence score .................................................

      # Initialize ScoredData with the first 6 columns of "mi_CompileData2"
      ScoredData <- mi_CompileData2[,1:6]

      # Initialize a counter for incidence overrides
      IncidenceOverideCount <- 0

      # Define column range for MI Data (from the 6th to the last column of mi_CompileData2)
      colIndex <- seq(7, ncol(mi_CompileData2))

      # Iterate over each column for scoring and adjustments
      for (i in colIndex){
        colName <- colnames(mi_CompileData2)[i]
        ScoredData[[colName]] <- NA

        #Score Severity # changing the current severity value in MISEV column???????????
        # Score Severity based on mi_CompileData2 #

        x <- ifelse(mi_CompileData2[,i] == 5, 5,
                    ifelse(mi_CompileData2[,i] > 3, 3,
                           ifelse(mi_CompileData2[,i] == 3, 2,
                                  ifelse(mi_CompileData2[,i] > 0, 1, 0))))

        # x <- ifelse(mi_CompileData2[,i]>3,3,
        #             ifelse(mi_CompileData2[,i]==3,2,
        #                    ifelse(mi_CompileData2[,i]>0,1,0)))

        ScoredData[,colName] <-x

        # Update mi_CompileData2 with the values from ScoredData for the current column
        mi_CompileData2[,colName] <- x

        #Check the Incidence percentage for each group
          for (sex in c('M','F')) {
            #studyDataStudyIndex <- which(mi_CompileData2$STUDYID == Study)
            studyDataStudyIndex <- which(mi_CompileData2$STUDYID == unique(ScoredData$STUDYID))
            studyDataSexIndex <- which(mi_CompileData2$SEX == sex)
            studyDataIndex <- intersect(studyDataStudyIndex, studyDataSexIndex)
            StudyData <- mi_CompileData2[studyDataIndex,]

            #MIIncidStudyIndex <- grep(Study, MIIncidence$Treatment)
            MIIncidStudyIndex <- grep(unique(ScoredData$STUDYID), MIIncidence$Treatment)
            MIIncidSexIndex <- which(MIIncidence$Sex == sex)
            MIIncidIndex <- intersect(MIIncidStudyIndex, MIIncidSexIndex)
            MIIncidStudy <- MIIncidence[MIIncidIndex,]

            for (Dose2 in unique(StudyData$ARMCD)){
              DoseSevIndex <- which(StudyData$ARMCD == Dose2)
              DoseSev <- StudyData[DoseSevIndex,]
              DoseIncid <- MIIncidStudy[which(stringr::word(MIIncidStudy$Treatment, -1) == Dose2),]
              if (colName %in% DoseIncid$Finding) {
                findingIndex <- which(DoseIncid$Finding == colName)

                Incid <- DoseIncid$Count[findingIndex]
                Incid <- ifelse(Incid >= 0.75, 5,
                                ifelse(Incid >= 0.5, 3,
                                       ifelse(Incid >= 0.25, 2,
                                              ifelse(Incid >= 0.1, 1, 0))))

                # Incid <- ifelse(Incid>=0.5,3,
                #                 ifelse(Incid>=0.25,2,
                #                        ifelse(Incid>=0.1,1,0)))
                swapIndex <- which(DoseSev[[colName]] < Incid & DoseSev[[colName]] > 0)
                if (length(swapIndex) > 0) {
                  DoseSev[swapIndex, colName] <- Incid
                  ScoredData[studyDataIndex[DoseSevIndex], colName] <- DoseSev[, colName]
                  IncidenceOverideCount <- IncidenceOverideCount + 1
                }

              }
            }
          }
      }

      # Per-subject-per-endpoint long format (all subjects, all arms)
      ScoredData_for_long <- ScoredData
      ScoredData_for_long[, 7:ncol(ScoredData_for_long)] <- lapply(
        ScoredData_for_long[, 7:ncol(ScoredData_for_long), drop = FALSE],
        function(x) as.numeric(as.character(x))
      )
      num_cols <- ncol(ScoredData_for_long)
      mi_per_subject_endpoint <- ScoredData_for_long %>%
        tidyr::pivot_longer(
          cols = 7:num_cols,
          names_to = "endpoint",
          values_to = "score"
        ) %>%
        dplyr::select(STUDYID, USUBJID, ARMCD, SETCD, SEX, endpoint, score) %>%
        dplyr::mutate(.armcd_ord = armcd_sort_key(.data$ARMCD)) %>%
        dplyr::arrange(.data$STUDYID, .data$endpoint, .data$.armcd_ord, .data$USUBJID) %>%
        dplyr::select(-.data$.armcd_ord)
      # highest_score for study-level MI: use full ScoredData (all subjects)
      if (num_cols == 7) {
        ScoredData_for_long$highest_score <- ScoredData_for_long[, 7]
      } else {
        ScoredData_for_long$highest_score <- matrixStats::rowMaxs(
          as.matrix(ScoredData_for_long[, 7:num_cols]), na.rm = TRUE
        )
      }
      mi_wide_per_subject <- ScoredData_for_long %>%
        dplyr::mutate(.armcd_ord = armcd_sort_key(.data$ARMCD)) %>%
        dplyr::arrange(.data$STUDYID, .data$.armcd_ord, .data$USUBJID) %>%
        dplyr::select(-.data$.armcd_ord)

      # subset the ScoredData
      ScoredData_subset_HD <- ScoredData %>% dplyr::filter (ARMCD == "HD")

      # Convert columns from 7th to the last to numeric
      ScoredData_subset_HD[, 7:ncol(ScoredData_subset_HD)] <- lapply(
        ScoredData_subset_HD[, 7:ncol(ScoredData_subset_HD)],
        function(x) as.numeric(as.character(x))
      )

      # @~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      if(score_in_list_format == FALSE) {
      # Study-level MI_final_score from full ScoredData (all subjects)
      MI_final_score <- ScoredData_for_long %>%
        dplyr::mutate(highest_score = as.numeric(highest_score)) %>%
        dplyr::group_by(STUDYID) %>%
        dplyr::summarise(avg_MI_score = mean(highest_score, na.rm = TRUE)) %>%
        dplyr::select(STUDYID, avg_MI_score)

      MI_df <- MI_final_score %>% dplyr::rename(MI_score = avg_MI_score)

      calculated_MI_value <- MI_df$MI_score[MI_df$STUDYID == unique(mi$STUDYID)]

          } else {
      # Create MI_final_score data frame with STUDYID and avg_MI_score
      # avg_MI_score is set to 0 and STUDYID values are unique from mi$STUDYID
      MI_final_score <- data.frame(  STUDYID = unique(mi$STUDYID), avg_MI_score = NA)

      # Append the "MI_score" to the "FOUR_Liver_Score" data frame
      MI_df <- MI_final_score %>% dplyr::rename(MI_score = avg_MI_score)

      # Extract the MI_score value for the current STUDYID from MI_df
      calculated_MI_value <- MI_df$MI_score
    }

  calculated_mi_score <- calculated_MI_value 
    }
  # @~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # @~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # if score_in_list_format is TRUE 
  if (score_in_list_format == TRUE) {
    
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      #~~~~~~~~~~ GET all the severity as individual in a list ~~~~~~~~~~~~~~~
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      
      # Working with "ScoredData_subset_HD " according to Kevin's advise
      # Create a variable for "ScoredData_subset_HD" data frame
      mi_scoredata_hd <- ScoredData_subset_HD # @~~~~~~~~~~~~~~~~~
      
      #Average calculation for each of the 7th column to onward.
      
      # Select columns from 7th to the last
      col_7th_to_end <- mi_scoredata_hd[, 7:length(colnames(mi_scoredata_hd)),
                                        drop = FALSE]
      
      # Calculate the mean for each selected column
      mean_col_7th_to_end <- lapply(col_7th_to_end, mean)
      
      # Define  an empty list
      empty_mi_score_list <- list()
      
      # Add a 'STUDYID' element to the empty_list  with value 'j'
      empty_mi_score_list[['STUDYID']] <- unique(mi$STUDYID)
      
      # Append elements from mean_col_7th_to_end to 
      mi_score_final_list <- append(empty_mi_score_list, mean_col_7th_to_end)
      
      # Convert the list to data frame 
      mi_score_final_list_df <- dplyr::bind_rows(mi_score_final_list, .id = "iteration")
      
      
    } else {
      #mi_score_final_list_df <- tibble::tibble()
      mi_score_final_list_df <- data.frame()
    }
  
  
  # Return based on score_in_list_format
  if (score_in_list_format) {
    return(mi_wide_per_subject)
  } else {
    return(mi_per_subject_endpoint)
  }

}
